---
# For now, only installing Exim on Debian. CentOS has postfix already.
- name: apt update
  apt: update_cache=yes
  changed_when: false
  when: ansible_os_family == "Debian"

- name: install email packages (Debian)
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ wordpress_packages_exim }}"
  when: ansible_os_family == "Debian"

- name: exim internet email
  lineinfile:
    path: "{{ wordpress_exim_config_file }}"
    regexp: "^dc_eximconfig_configtype='local'"
    line: "dc_eximconfig_configtype='internet'"
    backrefs: true
  notify: restart exim
  when: ansible_os_family == "Debian"
