---

- name: apt update 
  apt: update_cache=yes 
  changed_when: False
  when: ansible_os_family == "Debian"

- name: install general packages (Debian)
  apt:
    name: "{{ wordpress_packages_general }}"
    state: present
  when: ansible_os_family == "Debian"

- name: install general packages (RHEL)
  yum:
    name: "{{ wordpress_packages_general }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"
